// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-covenant.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.1";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function supabaseAnon() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated." }],
    isError: true
  };
}
function dbError(message) {
  return {
    content: [{ type: "text", text: `Database error: ${message}` }],
    isError: true
  };
}

// src/lib/mcp/tools/get-covenant.ts
var get_covenant_default = defineTool({
  name: "get_covenant",
  title: "Get giving covenant",
  description: "Return the signed-in user's giving covenant: percent of monthly profit committed, monthly minimum, auto-transfer flag, and their chosen scripture anchor.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const { data, error } = await supabaseForUser(ctx).from("giving_covenants").select("percent_of_profit, minimum_monthly, auto_transfer, scripture_anchor, updated_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return dbError(error.message);
    if (!data) {
      return {
        content: [{ type: "text", text: "No covenant set yet." }],
        structuredContent: { covenant: null }
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { covenant: data }
    };
  }
});

// src/lib/mcp/tools/list-recipients.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
var list_recipients_default = defineTool2({
  name: "list_recipients",
  title: "List giving recipients",
  description: "List the signed-in user's chosen giving recipients (church, missions, nonprofits) with allocation percentages, verification status, and their giving-page URL when known.",
  inputSchema: {
    include_unverified: z.boolean().default(true).describe("Include recipients that have not been verified yet. Defaults to true.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_unverified }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    let query = supabaseForUser(ctx).from("giving_recipients").select(
      "id, name, type, allocation_percent, ein, platform, donate_url, website, verification_status, verified_name, church_id, notes, created_at"
    ).eq("user_id", ctx.getUserId()).order("allocation_percent", { ascending: false });
    if (!include_unverified) query = query.eq("verification_status", "verified");
    const { data, error } = await query;
    if (error) return dbError(error.message);
    const total = (data ?? []).reduce((s, r) => s + Number(r.allocation_percent ?? 0), 0);
    return {
      content: [
        { type: "text", text: JSON.stringify({ recipients: data, allocation_total: total }, null, 2) }
      ],
      structuredContent: { recipients: data ?? [], allocation_total: total }
    };
  }
});

// src/lib/mcp/tools/list-monthly-summaries.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_monthly_summaries_default = defineTool3({
  name: "list_monthly_summaries",
  title: "List monthly summaries",
  description: "List monthly profit/giving summaries for the signed-in user. Excludes sample data by default.",
  inputSchema: {
    limit: z2.number().int().min(1).max(60).default(12).describe("Max months to return (default 12)."),
    include_sample: z2.boolean().default(false).describe("Include sample/demo data. Defaults to false."),
    year: z2.number().int().min(2e3).max(2100).nullable().default(null).describe("Filter to a specific calendar year, or null for all years.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, include_sample, year }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    let q = supabaseForUser(ctx).from("monthly_summaries").select("id, month, total_revenue, total_expenses, net_profit, giving_percent, giving_amount, status, source, is_sample, reviewed_at, created_at").eq("user_id", ctx.getUserId()).order("month", { ascending: false }).limit(limit);
    if (!include_sample) q = q.eq("is_sample", false);
    if (year != null) q = q.gte("month", `${year}-01-01`).lt("month", `${year + 1}-01-01`);
    const { data, error } = await q;
    if (error) return dbError(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify({ summaries: data }, null, 2) }],
      structuredContent: { summaries: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-transactions.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_transactions_default = defineTool4({
  name: "list_transactions",
  title: "List giving transactions",
  description: "List individual gift transactions for the signed-in user. Steward never moves money; each transaction records a gift the user made through the recipient's own giving page.",
  inputSchema: {
    limit: z3.number().int().min(1).max(200).default(50),
    status: z3.enum(["pending", "completed", "transferred", "all"]).default("all"),
    include_sample: z3.boolean().default(false)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status, include_sample }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    let q = supabaseForUser(ctx).from("giving_transactions").select("id, recipient_id, monthly_summary_id, amount, status, payment_method, marked_paid_at, transferred_at, is_sample, created_at").order("created_at", { ascending: false }).limit(limit);
    if (status !== "all") q = q.eq("status", status);
    if (!include_sample) q = q.eq("is_sample", false);
    const { data, error } = await q;
    if (error) return dbError(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify({ transactions: data }, null, 2) }],
      structuredContent: { transactions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-ytd-summary.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
var get_ytd_summary_default = defineTool5({
  name: "get_ytd_summary",
  title: "Get YTD giving summary",
  description: "Return a year-to-date rollup for the signed-in user: total revenue, total expenses, net profit, total giving, and per-recipient breakdown. Excludes sample data.",
  inputSchema: {
    year: z4.number().int().min(2e3).max(2100).nullable().default(null).describe("Calendar year. Defaults to the current year.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ year }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const y = year ?? (/* @__PURE__ */ new Date()).getUTCFullYear();
    const sb = supabaseForUser(ctx);
    const uid = ctx.getUserId();
    const { data: summaries, error: sErr } = await sb.from("monthly_summaries").select("id, month, total_revenue, total_expenses, net_profit, giving_amount, status").eq("user_id", uid).eq("is_sample", false).gte("month", `${y}-01-01`).lt("month", `${y + 1}-01-01`);
    if (sErr) return dbError(sErr.message);
    const summaryIds = (summaries ?? []).map((s) => s.id);
    let byRecipient = {};
    if (summaryIds.length) {
      const { data: txs, error: tErr } = await sb.from("giving_transactions").select("amount, status, recipient_id").in("monthly_summary_id", summaryIds).eq("is_sample", false).in("status", ["completed", "transferred"]);
      if (tErr) return dbError(tErr.message);
      const recipientIds = Array.from(new Set((txs ?? []).map((t) => t.recipient_id)));
      const { data: recips } = recipientIds.length ? await sb.from("giving_recipients").select("id, name, verified_name").in("id", recipientIds) : { data: [] };
      const nameById = new Map((recips ?? []).map((r) => [r.id, r.verified_name || r.name]));
      for (const t of txs ?? []) {
        const key = t.recipient_id;
        if (!byRecipient[key]) byRecipient[key] = { amount: 0, name: nameById.get(key) };
        byRecipient[key].amount += Number(t.amount ?? 0);
      }
    }
    const totals = (summaries ?? []).reduce(
      (acc, s) => ({
        revenue: acc.revenue + Number(s.total_revenue ?? 0),
        expenses: acc.expenses + Number(s.total_expenses ?? 0),
        profit: acc.profit + Number(s.net_profit ?? 0),
        giving_planned: acc.giving_planned + Number(s.giving_amount ?? 0)
      }),
      { revenue: 0, expenses: 0, profit: 0, giving_planned: 0 }
    );
    const giving_sent = Object.values(byRecipient).reduce((s, r) => s + r.amount, 0);
    const result = {
      year: y,
      months_recorded: summaries?.length ?? 0,
      totals: { ...totals, giving_sent },
      by_recipient: Object.entries(byRecipient).map(([id, v]) => ({
        recipient_id: id,
        name: v.name,
        amount: v.amount
      }))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/search-churches.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^4.4.3";
var search_churches_default = defineTool6({
  name: "search_churches",
  title: "Search church directory",
  description: "Search Steward's public church directory by name, alias, city, state, or pastor. Returns basic identity plus known giving platform info so the caller can point users toward the right giving page.",
  inputSchema: {
    query: z5.string().trim().min(2).max(120).describe("Search text \u2014 name, alias, or pastor name."),
    state: z5.string().trim().length(2).nullable().default(null).describe("Optional 2-letter US state filter."),
    limit: z5.number().int().min(1).max(25).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query, state, limit }) => {
    const sb = supabaseAnon();
    const q = query.replace(/[,()"']/g, " ").trim();
    const pattern = `%${q}%`;
    let req = sb.from("churches").select("id, legal_name, dba_name, aliases, city, state, denomination, website, giving_platform, giving_url, pastor_name, verification_status").or(
      `legal_name.ilike.${pattern},dba_name.ilike.${pattern},pastor_name.ilike.${pattern},aliases.cs.{${q}}`
    ).limit(limit);
    if (state) req = req.eq("state", state.toUpperCase());
    const { data, error } = await req;
    if (error) return dbError(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify({ churches: data }, null, 2) }],
      structuredContent: { churches: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-profile.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_profile_default = defineTool7({
  name: "get_profile",
  title: "Get profile",
  description: "Return the signed-in Steward user's profile: full name, business name, business type, and onboarding status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const { data, error } = await supabaseForUser(ctx).from("profiles").select("full_name, business_name, business_type, onboarded, created_at").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return dbError(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ilbyouqfvcjhpnhyetkz";
var mcp_default = defineMcp({
  name: "steward-mcp",
  title: "Steward",
  version: "0.1.0",
  instructions: "Read-only tools for a Steward user's stewardship data: giving covenant, chosen recipients, monthly summaries, individual gift transactions, YTD totals, and the public church directory. All per-user tools act as the signed-in user and are scoped by RLS. Steward never moves money \u2014 use these tools for reporting, analysis, and pastoral encouragement, not to initiate transfers.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_profile_default,
    get_covenant_default,
    list_recipients_default,
    list_monthly_summaries_default,
    list_transactions_default,
    get_ytd_summary_default,
    search_churches_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
